name: Bug report
description: Create a bug report
title: "[Bug]: "
labels: ["bug"]

body:
  # Bug information
  - type: input
    id: name
    attributes:
      label: Name
      description: >
        Name of package containing the bug
    validations:
      required: true
  - type: textarea
    id: platform
    attributes:
      label: Platform
      description: >
        Fields to create a complete report
      placeholder: |
        - Operating system
        - Package manager
        - Package type
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: >
        Description of what the bug is
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction
      description: >
        Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  # Options
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: >
        Description of what expected to happen
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: >
        Add screenshots to help explain the bug
  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: >
        Add any other context about the bug if it is necessary
