if($<CONFIG> STREQUAL "Debug")
    set(REDIMAGETOOL_CONFIG "Debug")
elseif($<CONFIG> STREQUAL "Release" OR $<CONFIG> STREQUAL "MinSizeRel" OR $<CONFIG> STREQUAL "RelWithDebInfo")
    set(REDIMAGETOOL_CONFIG "Release")
endif()

set(REDIMAGETOOL_ROOT_PATH "${CMAKE_CURRENT_SOURCE_DIR}/../..")
set(REDIMAGETOOL_RUNTIME_ID "win-x86")
set(REDIMAGETOOL_RUNTIME_PATH "${REDIMAGETOOL_ROOT_PATH}/runtimes/${REDIMAGETOOL_RUNTIME_ID}/native/${REDIMAGETOOL_CONFIG}/")

add_custom_command(TARGET ${PROJECT_NAME}
    POST_BUILD
    COMMAND ${CMAKE_COMMAND} -E copy_if_different ${REDIMAGETOOL_RUNTIME_PATH}/RedImageTool.pdb ${CMAKE_RUNTIME_OUTPUT_DIRECTORY}/
)
